class AddDefaultData < ActiveRecord::Migration
  def self.up
      Posting.create( :title => "Welcome", :body => "Welcome,\nDatabase installed successfully", 
                      :author_id => 1, :date_expires => DateTime.now()+10.years )

      Author.create( 
        :nickname => 'Nockenfell',
        :prename  => 'Andreas',
        :lastname => 'Altendorfer',
        :secret   => Digest::SHA1.hexdigest(DEFAULT_ROOT_PASSWORD)[0..39],
        :date_birth=>Date::civil( 1964,8,31 ),
        :gender   => 2,
        :country  => 13,
        :address  => 'Am Damm 6',
        :zip      => '4053',
        :city     => 'Haid',
        :email    => 'n0ckenfell@mac.com',
        :phone    => 'n/a',
        :chat     => 'n0ckenfell@mac.com',
        :note     => 'Author of iBoard2.0',
        :user_id  => 1
      )
      
      u = User.create( :username => 'root', :longname => 'Administrator', :password => Digest::SHA1.hexdigest(DEFAULT_ROOT_PASSWORD)[0..39])
      u.save_without_validation!
      
      
      defaults = [
          ['root', 'This allows everything'],
          ['binaries', 'Binary Controller Access'],
          ['registered users', 'this will be autoassigned at register confirmation'],
          ['postings', 'Posting Controller Access'],
          ['functions','Functions Controller Access'],
          ['page_columns', 'Page Columns Controller Access'],
          ['div_tags', 'DIV-Tags Controller Access'],
          ['users', 'Users Controller Access'],
          ['accessors', 'Accessors Controller Access'],
          ['galleries', 'Gallery Controller Access'],
          ['content', 'Allowed to edit content'],
          ['read all', 'Everything is readable'],
          ['edit posting', 'Allowed to edit postings'],
          ['new posting', 'Allowed to write new postings'],
          ['Edit layout', 'Allowed to edit layouts'],
          ['Edit pages', 'Allowed to edit Pages'],
        ]
      defaults.each do |d|
        f = Function.create(:name => d[0], :comment => d[1])
        Accessor.create(:name => "root:#{d[0]}", :comment => 'autogenerated at db:migrate',
                        :user_id => 1, :function_id => f.id )
      end
      
      Page.create(:name => 'Frontpage', :introduction => 'Welcome to *iBoard _2.0_*', :show_title => true, :show_introduction => true, :div_tag_id => 1)
      
      DivTag.create(:name => 'Default', :definition => 'font-family: Arial; font-size: normal; color: black;')
      
      users = User.find(:all)
      users.each do |usr|
        usr.email = "please set your email-address"
      end
  end

  def self.down
  end
end
